version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    environment:
     - TZ=Asia/Calcutta
    restart: always 
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - TZ=Asia/Calcutta
    restart: always 
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - TZ=Asia/Calcutta
    restart: always 
  mysqldestination:
    build: ./mysql-log-replication-enable
    ports:
     - 3307:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - TZ=Asia/Calcutta
    restart: always
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    volumes:
       - ./confluent-jdbc-data:/kafka/connect/confluent-jdbc-data
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
     - mysqldestination
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - TZ=Asia/Calcutta
     #- CONNECT_PLUGIN_PATH=/kafka/libs,/kafka/connect
    restart: always 